// Code generated by ent, DO NOT EDIT.

package startedpoll

import (
	"poll-app/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldLTE(FieldID, id))
}

// PollID applies equality check predicate on the "poll_id" field. It's identical to PollIDEQ.
func PollID(v int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldPollID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldUserID, v))
}

// Completed applies equality check predicate on the "completed" field. It's identical to CompletedEQ.
func Completed(v bool) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldCompleted, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldUpdatedAt, v))
}

// PollIDEQ applies the EQ predicate on the "poll_id" field.
func PollIDEQ(v int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldPollID, v))
}

// PollIDNEQ applies the NEQ predicate on the "poll_id" field.
func PollIDNEQ(v int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNEQ(FieldPollID, v))
}

// PollIDIn applies the In predicate on the "poll_id" field.
func PollIDIn(vs ...int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldIn(FieldPollID, vs...))
}

// PollIDNotIn applies the NotIn predicate on the "poll_id" field.
func PollIDNotIn(vs ...int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNotIn(FieldPollID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNotIn(FieldUserID, vs...))
}

// CompletedEQ applies the EQ predicate on the "completed" field.
func CompletedEQ(v bool) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldCompleted, v))
}

// CompletedNEQ applies the NEQ predicate on the "completed" field.
func CompletedNEQ(v bool) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNEQ(FieldCompleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StartedPoll {
	return predicate.StartedPoll(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPoll applies the HasEdge predicate on the "poll" edge.
func HasPoll() predicate.StartedPoll {
	return predicate.StartedPoll(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PollTable, PollColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPollWith applies the HasEdge predicate on the "poll" edge with a given conditions (other predicates).
func HasPollWith(preds ...predicate.Poll) predicate.StartedPoll {
	return predicate.StartedPoll(func(s *sql.Selector) {
		step := newPollStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.StartedPoll {
	return predicate.StartedPoll(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.StartedPoll {
	return predicate.StartedPoll(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCompletedQuestions applies the HasEdge predicate on the "completed_questions" edge.
func HasCompletedQuestions() predicate.StartedPoll {
	return predicate.StartedPoll(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CompletedQuestionsTable, CompletedQuestionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompletedQuestionsWith applies the HasEdge predicate on the "completed_questions" edge with a given conditions (other predicates).
func HasCompletedQuestionsWith(preds ...predicate.CompletedQuestion) predicate.StartedPoll {
	return predicate.StartedPoll(func(s *sql.Selector) {
		step := newCompletedQuestionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StartedPoll) predicate.StartedPoll {
	return predicate.StartedPoll(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StartedPoll) predicate.StartedPoll {
	return predicate.StartedPoll(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StartedPoll) predicate.StartedPoll {
	return predicate.StartedPoll(sql.NotPredicates(p))
}
