// Code generated by ent, DO NOT EDIT.

package ent

import (
	"poll-app/ent/poll"
	"poll-app/ent/question"
	"poll-app/ent/questionoption"
	"poll-app/ent/schema"
	"poll-app/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pollFields := schema.Poll{}.Fields()
	_ = pollFields
	// pollDescCompleted is the schema descriptor for completed field.
	pollDescCompleted := pollFields[2].Descriptor()
	// poll.DefaultCompleted holds the default value on creation for the completed field.
	poll.DefaultCompleted = pollDescCompleted.Default.(bool)
	// pollDescCreatedAt is the schema descriptor for created_at field.
	pollDescCreatedAt := pollFields[3].Descriptor()
	// poll.DefaultCreatedAt holds the default value on creation for the created_at field.
	poll.DefaultCreatedAt = pollDescCreatedAt.Default.(func() time.Time)
	// pollDescUpdatedAt is the schema descriptor for updated_at field.
	pollDescUpdatedAt := pollFields[4].Descriptor()
	// poll.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	poll.DefaultUpdatedAt = pollDescUpdatedAt.Default.(func() time.Time)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescHead is the schema descriptor for head field.
	questionDescHead := questionFields[1].Descriptor()
	// question.DefaultHead holds the default value on creation for the head field.
	question.DefaultHead = questionDescHead.Default.(bool)
	// questionDescNumOfAnswers is the schema descriptor for num_of_answers field.
	questionDescNumOfAnswers := questionFields[2].Descriptor()
	// question.DefaultNumOfAnswers holds the default value on creation for the num_of_answers field.
	question.DefaultNumOfAnswers = questionDescNumOfAnswers.Default.(int)
	// questionDescCreatedAt is the schema descriptor for created_at field.
	questionDescCreatedAt := questionFields[3].Descriptor()
	// question.DefaultCreatedAt holds the default value on creation for the created_at field.
	question.DefaultCreatedAt = questionDescCreatedAt.Default.(func() time.Time)
	// questionDescUpdatedAt is the schema descriptor for updated_at field.
	questionDescUpdatedAt := questionFields[4].Descriptor()
	// question.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	question.DefaultUpdatedAt = questionDescUpdatedAt.Default.(func() time.Time)
	questionoptionFields := schema.QuestionOption{}.Fields()
	_ = questionoptionFields
	// questionoptionDescChosen is the schema descriptor for chosen field.
	questionoptionDescChosen := questionoptionFields[1].Descriptor()
	// questionoption.DefaultChosen holds the default value on creation for the chosen field.
	questionoption.DefaultChosen = questionoptionDescChosen.Default.(bool)
	// questionoptionDescCreatedAt is the schema descriptor for created_at field.
	questionoptionDescCreatedAt := questionoptionFields[2].Descriptor()
	// questionoption.DefaultCreatedAt holds the default value on creation for the created_at field.
	questionoption.DefaultCreatedAt = questionoptionDescCreatedAt.Default.(func() time.Time)
	// questionoptionDescUpdatedAt is the schema descriptor for updated_at field.
	questionoptionDescUpdatedAt := questionoptionFields[3].Descriptor()
	// questionoption.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	questionoption.DefaultUpdatedAt = questionoptionDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
