// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"poll-app/ent/predicate"
	"poll-app/ent/startedpoll"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StartedPollDelete is the builder for deleting a StartedPoll entity.
type StartedPollDelete struct {
	config
	hooks    []Hook
	mutation *StartedPollMutation
}

// Where appends a list predicates to the StartedPollDelete builder.
func (spd *StartedPollDelete) Where(ps ...predicate.StartedPoll) *StartedPollDelete {
	spd.mutation.Where(ps...)
	return spd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (spd *StartedPollDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, spd.sqlExec, spd.mutation, spd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (spd *StartedPollDelete) ExecX(ctx context.Context) int {
	n, err := spd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (spd *StartedPollDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(startedpoll.Table, sqlgraph.NewFieldSpec(startedpoll.FieldID, field.TypeInt))
	if ps := spd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, spd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	spd.mutation.done = true
	return affected, err
}

// StartedPollDeleteOne is the builder for deleting a single StartedPoll entity.
type StartedPollDeleteOne struct {
	spd *StartedPollDelete
}

// Where appends a list predicates to the StartedPollDelete builder.
func (spdo *StartedPollDeleteOne) Where(ps ...predicate.StartedPoll) *StartedPollDeleteOne {
	spdo.spd.mutation.Where(ps...)
	return spdo
}

// Exec executes the deletion query.
func (spdo *StartedPollDeleteOne) Exec(ctx context.Context) error {
	n, err := spdo.spd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{startedpoll.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (spdo *StartedPollDeleteOne) ExecX(ctx context.Context) {
	if err := spdo.Exec(ctx); err != nil {
		panic(err)
	}
}
