// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Poll is the predicate function for poll builders.
type Poll func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// QuestionOption is the predicate function for questionoption builders.
type QuestionOption func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
